In [44]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
y_true = ["hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "hook", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab", "jab",  "jab", "jab", "jab", "jab", "jab", "jab", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut"]
y_pred = ["jab", "hook", "hook", "hook", "hook", "hook", "jab", "hook", "hook", "jab", "hook", "hook", "hook", "jab", "jab", "jab", "hook", "hook", "hook", "hook", "uppercut", "kick", "jab", "uppercut", "hook", "uppercut", "jab", "jab", "jab", "hook", "uppercut", "hook", "hook", "hook", "jab", "jab", "hook", "jab", "hook", "hook", "jab", "jab", "hook", "jab",  "jab", "hook", "jab", "jab", "uppercut", "jab", "kick", "jab", "uppercut", "hook", "kick", "jab", "kick", "uppercut", "uppercut", "kick", "kick", "kick", "kick", "kick", "uppercut", "kick", "kick", "kick", "kick", "kick", "kick", "kick", "uppercut", "hook", "jab", "hook", "hook", "uppercut", "hook", "uppercut", "hook", "uppercut", "hook", "uppercut", "uppercut", "jab", "hook", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "uppercut", "hook", "hook", "jab", "hook"]
confusion_matrix(y_true, y_pred, labels=["hook", "jab", "kick", "uppercut"])

array([[15,  7,  1,  2],
       [ 9, 13,  0,  3],
       [ 2,  3, 15,  5],
       [ 9,  2,  0, 14]], dtype=int64)

In [45]:
recall_score(y_true, y_pred, average='macro') 

0.57000000000000006

In [46]:
recall_score(y_true, y_pred, average='micro') 

0.56999999999999995

In [47]:
recall_score(y_true, y_pred, average='weighted')

0.56999999999999995

In [48]:
recall_score(y_true, y_pred, average=None)

array([ 0.6 ,  0.52,  0.6 ,  0.56])

In [49]:
accuracy_score(y_true, y_pred)

0.56999999999999995

In [51]:
print(classification_report(y_true, y_pred))

             precision    recall  f1-score   support

       hook       0.43      0.60      0.50        25
        jab       0.52      0.52      0.52        25
       kick       0.94      0.60      0.73        25
   uppercut       0.58      0.56      0.57        25

avg / total       0.62      0.57      0.58       100



In [52]:
from sklearn.metrics import precision_score

In [53]:
precision_score(y_true, y_pred, average='macro')

0.61735119047619047

In [54]:
precision_score(y_true, y_pred, average='micro')

0.56999999999999995

In [55]:
precision_score(y_true, y_pred, average='weighted')

0.61735119047619047

In [56]:
precision_score(y_true, y_pred, average=None)

array([ 0.42857143,  0.52      ,  0.9375    ,  0.58333333])

In [57]:
from sklearn.metrics import f1_score

In [58]:
f1_score(y_true, y_pred, average='macro')

0.58078397212543553

In [59]:
f1_score(y_true, y_pred, average='micro')

0.56999999999999995

In [60]:
f1_score(y_true, y_pred, average='weighted')

0.58078397212543553

In [61]:
f1_score(y_true, y_pred, average=None)

array([ 0.5       ,  0.52      ,  0.73170732,  0.57142857])