In [43]:
import numpy as np

In [44]:
outlook = np.array([0, 0, 1, 0, 1, 1, 0]) 
#sunny = 0 , cloudy = 1
temperature = np.array ([0, 1, 1, 1, 0, 0, 0])
#cold = 0, warm = 1
routine = np.array([0, 1, 0, 0 ,0, 1, 1])
#indoor = 0, outdoor = 1
coat = np.array ([0, 0, 0, 0, 1, 1, 1])
#no = 0, yes = 1

In [45]:
x = (1, 1, 1)
# cloudy , warm , outdoor

# c = yes

In [46]:
a_1 = np.argwhere (coat == 1)
print (a_1)

[[4]
 [5]
 [6]]


In [47]:
b_1 = outlook[4:]
print (b_1)

[1 1 0]


In [48]:
c_1 = temperature [4:]
print (c_1)

[0 0 0]


In [49]:
d_1 = routine [4:]
print(d_1)

[0 1 1]


In [50]:
e_1 =np.argwhere(b_1==1)
print(e_1)

[[0]
 [1]]


In [51]:
f_1 =np.argwhere(c_1==1)
print(f_1)

[]


In [52]:
g_1=np.argwhere(d_1==1)
print(g_1)

[[1]
 [2]]


In [53]:
w_1 = ((len(e_1)/len(a_1))*(len(f_1)/len(a_1))*(len(g_1)/len(a_1))*(len(a_1)/len(coat)))
print(w_1)

0.0


In [54]:
h_1 = np.argwhere(outlook==1)
print(h_1)

[[2]
 [4]
 [5]]


In [55]:
i_1 = np.argwhere(temperature==1)
print(i_1)

[[1]
 [2]
 [3]]


In [56]:
j_1 = np.argwhere(routine==1)
print(j_1)

[[1]
 [5]
 [6]]


In [57]:
v_1=(len(h_1)/len(outlook))*(len(i_1)/len(temperature))*(len(j_1)/len(routine))
print(v_1)

0.07871720116618075


In [58]:
z_1 = (w_1/v_1)
print (z_1)

0.0


#  c = no

In [59]:
a_0 = np.argwhere (coat == 0)
print (a_0)

[[0]
 [1]
 [2]
 [3]]


In [60]:
b_0 = outlook[:4]
print (b_0)

[0 0 1 0]


In [61]:
c_0 = temperature [:4]
print (c_0)

[0 1 1 1]


In [62]:
d_0 = routine [:4]
print(d_0)

[0 1 0 0]


In [63]:
e_0 =np.argwhere(b_0 ==0)
print(e_0)

[[0]
 [1]
 [3]]


In [64]:
f_0 =np.argwhere(c_0==0)
print(f_0)

[[0]]


In [65]:
g_0=np.argwhere(d_0==0)
print(g_0)

[[0]
 [2]
 [3]]


In [66]:
w_0 = ((len(e_0)/len(a_0))*(len(f_0)/len(a_0))*(len(g_0)/len(a_0))*(len(a_0)/len(coat)))
print(w_0)

0.08035714285714285


In [67]:
h_0 = np.argwhere(outlook==0)
print(h_0)

[[0]
 [1]
 [3]
 [6]]


In [68]:
i_0 = np.argwhere(temperature==0)
print(i_0)

[[0]
 [4]
 [5]
 [6]]


In [69]:
j_0 = np.argwhere(routine==0)
print(j_0)

[[0]
 [2]
 [3]
 [4]]


In [70]:
v_0=(len(h_0)/len(outlook))*(len(i_0)/len(temperature))*(len(j_0)/len(routine))
print(v_0)

0.1865889212827988


In [71]:
z_0 = (w_0/v_0)
print (z_0)

0.43066406250000006


# condition 

In [72]:
if (z_1<z_0):
    print ("no")
else :
    print("yes")

no


In [ ]:
Shaikat Saha
id : 151-15-4698