In [76]:
import numpy as np

In [77]:
outlook = np.array(['sunny', 'sunny', 'cloudy', 'sunny', 'cloudy', 'cloudy', 'sunny']) 
#sunny = 0 , cloudy = 1
temperature = np.array (['cold', 'warm', 'warm', 'warm', 'cold', 'cold', 'cold'])
#cold = 0, warm = 1
routine = np.array(['indoor', 'outdoor', 'indoor', 'indoor' ,'indoor', 'outdoor', 'outdoor'])
#indoor = 0, outdoor = 1
coat = np.array (['no', 'no', 'no', 'no', 'yes', 'yes', 'yes'])
#no = 0, yes = 1

In [78]:
x = ('cloudy', 'warm', 'outdoor')
# cloudy , warm , outdoor

# c = yes

In [79]:
a_1 = np.argwhere (coat == 'yes')
print (a_1)

[[4]
 [5]
 [6]]


In [80]:
b_1 = outlook[4:]
print (b_1)

['cloudy' 'cloudy' 'sunny']


In [81]:
c_1 = temperature [4:]
print (c_1)

['cold' 'cold' 'cold']


In [82]:
d_1 = routine [4:]
print(d_1)

['indoor' 'outdoor' 'outdoor']


In [83]:
e_1 =np.argwhere(b_1=='clouudy')
print(e_1)

[]


In [84]:
f_1 =np.argwhere(c_1=='cold')
print(f_1)

[[0]
 [1]
 [2]]


In [85]:
g_1=np.argwhere(d_1=='outdoor')
print(g_1)

[[1]
 [2]]


In [86]:
w_1 = ((len(e_1)/len(a_1))*(len(f_1)/len(a_1))*(len(g_1)/len(a_1))*(len(a_1)/len(coat)))
print(w_1)

0.0


In [87]:
h = np.argwhere(outlook=='cloudy')
print(h)

[[2]
 [4]
 [5]]


In [88]:
i = np.argwhere(temperature=='warm')
print(i)

[[1]
 [2]
 [3]]


In [89]:
j = np.argwhere(routine=='outdoor')
print(j)

[[1]
 [5]
 [6]]


In [90]:
v_1=(len(h)/len(outlook))*(len(i)/len(temperature))*(len(j)/len(routine))
print(v_1)

0.07871720116618075


In [91]:
z_1 = (w_1/v_1)
print (z_1)

0.0


#  c = no

In [92]:
a_0 = np.argwhere (coat == 'no')
print (a_0)

[[0]
 [1]
 [2]
 [3]]


In [93]:
b_0 = outlook[:4]
print (b_0)

['sunny' 'sunny' 'cloudy' 'sunny']


In [94]:
c_0 = temperature [:4]
print (c_0)

['cold' 'warm' 'warm' 'warm']


In [95]:
d_0 = routine [:4]
print(d_0)

['indoor' 'outdoor' 'indoor' 'indoor']


In [96]:
e_0 =np.argwhere(b_0 =='cloudy')
print(e_0)

[[2]]


In [97]:
f_0 =np.argwhere(c_0=='warm')
print(f_0)

[[1]
 [2]
 [3]]


In [98]:
g_0=np.argwhere(d_0=='outdoor')
print(g_0)

[[1]]


In [99]:
w_0 = ((len(e_0)/len(a_0))*(len(f_0)/len(a_0))*(len(g_0)/len(a_0))*(len(a_0)/len(coat)))
print(w_0)

0.026785714285714284


In [100]:
v_0=(len(h)/len(outlook))*(len(i)/len(temperature))*(len(j)/len(routine))
print(v_0)

0.07871720116618075


In [101]:
z_0 = (w_0/v_0)
print (z_0)

0.3402777777777778


# condition 

In [102]:
if (z_1<z_0):
    print ("no")
else :
    print("yes")

no


In [103]:
# shaikat saha
# id : 151-15-4698