In [103]:
import numpy as np

In [104]:
outlook = np.array([0, 0, 1, 0, 1, 1, 0]) 
#sunny = 0 , cloudy = 1
temperature = np.array ([0, 1, 1, 1, 0, 0, 0])
#cold = 0, warm = 1
routine = np.array([0, 1, 0, 0 ,0, 1, 1])
#indoor = 0, outdoor = 1
coat = np.array ([0, 0, 0, 0, 1, 1, 1])
#no = 0, yes = 1

In [105]:
x = (1, 1, 1)
# cloudy , warm , outdoor

# c = yes

In [106]:
a_1 = np.argwhere (coat == 1)
print (a_1)

[[4]
 [5]
 [6]]


In [107]:
b_1 = outlook[4:]
print (b_1)

[1 1 0]


In [108]:
c_1 = temperature [4:]
print (c_1)

[0 0 0]


In [109]:
d_1 = routine [4:]
print(d_1)

[0 1 1]


In [110]:
e_1 =np.argwhere(b_1==1)
print(e_1)

[[0]
 [1]]


In [111]:
f_1 =np.argwhere(c_1==1)
print(f_1)

[]


In [112]:
g_1=np.argwhere(d_1==1)
print(g_1)

[[1]
 [2]]


In [113]:
w_1 = ((len(e_1)/len(a_1))*(len(f_1)/len(a_1))*(len(g_1)/len(a_1))*(len(a_1)/len(coat)))
print(w_1)

0.0


In [114]:
h_1 = np.argwhere(outlook==1)
print(h_1)

[[2]
 [4]
 [5]]


In [115]:
i_1 = np.argwhere(temperature==1)
print(i_1)

[[1]
 [2]
 [3]]


In [116]:
j_1 = np.argwhere(routine==1)
print(j_1)

[[1]
 [5]
 [6]]


In [117]:
v_1=(len(h_1)/len(outlook))*(len(i_1)/len(temperature))*(len(j_1)/len(routine))
print(v_1)

0.07871720116618075


In [118]:
z_1 = (w_1/v_1)
print (z_1)

0.0


#  c = no

In [119]:
a_0 = np.argwhere (coat == 0)
print (a_0)

[[0]
 [1]
 [2]
 [3]]


In [120]:
b_0 = outlook[:4]
print (b_0)

[0 0 1 0]


In [121]:
c_0 = temperature [:4]
print (c_0)

[0 1 1 1]


In [122]:
d_0 = routine [:4]
print(d_0)

[0 1 0 0]


In [123]:
e_0 =np.argwhere(b_0 ==1)
print(e_0)

[[2]]


In [124]:
f_0 =np.argwhere(c_0==1)
print(f_0)

[[1]
 [2]
 [3]]


In [125]:
g_0=np.argwhere(d_0==1)
print(g_0)

[[1]]


In [126]:
w_0 = ((len(e_0)/len(a_0))*(len(f_0)/len(a_0))*(len(g_0)/len(a_0))*(len(a_0)/len(coat)))
print(w_0)

0.026785714285714284


In [127]:
h_0 = np.argwhere(outlook==1)
print(h_0)

[[2]
 [4]
 [5]]


In [128]:
i_0 = np.argwhere(temperature==1)
print(i_0)

[[1]
 [2]
 [3]]


In [129]:
j_0 = np.argwhere(routine==1)
print(j_0)

[[1]
 [5]
 [6]]


In [130]:
v_0=(len(h_0)/len(outlook))*(len(i_0)/len(temperature))*(len(j_0)/len(routine))
print(v_0)

0.07871720116618075


In [131]:
z_0 = (w_0/v_0)
print (z_0)

0.3402777777777778


# condition 

In [132]:
if (z_1<z_0):
    print ("no")
else :
    print("yes")

no


In [ ]:
shaikat saha
id : 151-15-4698